import type { APIRoute } from "astro";

export const GET: APIRoute = () => {
	const body =
		"---\ntitle: Moveroo Australia\ncanonical: https://moveroo.com.au/\ndescription: Moveroo Australia publishes agent-readable discovery resources for customer-authorised household moving quotes, vehicle transport quotes, callbacks, and quote API documentation.\nagent_resources:\n  - https://moveroo.com.au/agents/\n  - https://quotes.moveroo.com.au/agents/examples\n  - https://moveroo.com.au/llms.txt\n  - https://moveroo.com.au/.well-known/llms.txt\n  - https://moveroo.com.au/.well-known/ai-catalog.json\n  - https://moveroo.com.au/.well-known/agent-skills/index.json\nquote_host: https://quotes.moveroo.com.au\n---\n\n# Moveroo Australia\n\nMoveroo Australia publishes agent-readable discovery resources for customer-authorised household moving quotes, vehicle transport quotes, callbacks, and quote API documentation.\n\n## Agent and API Discovery\n\n- [Agent/API documentation](https://moveroo.com.au/agents/)\n- [Agent/API examples](https://quotes.moveroo.com.au/agents/examples)\n- [Agent skills index](https://moveroo.com.au/.well-known/agent-skills/index.json)\n- [LLM guidance](https://moveroo.com.au/llms.txt)\n- [Well-known LLM guidance](https://moveroo.com.au/.well-known/llms.txt)\n- [AI catalog](https://moveroo.com.au/.well-known/ai-catalog.json)\n- [Quote capability alias](https://moveroo.com.au/quote-capability.json)\n- [OpenAPI alias](https://moveroo.com.au/openapi.json)\n\n## Quote Actions\n\nThe canonical quote and callback API contract lives on the Moveroo Australia quote host at https://quotes.moveroo.com.au.\n\n- [Household quote form](https://quotes.moveroo.com.au/quote/household)\n- [Vehicle quote form](https://quotes.moveroo.com.au/quote/vehicle)\n- [Contact and callback page](https://quotes.moveroo.com.au/contact)\n- [Canonical Agent/API guide](https://quotes.moveroo.com.au/agents)\n- [Canonical Agent/API examples](https://quotes.moveroo.com.au/agents/examples)\n- [Canonical OpenAPI schema](https://quotes.moveroo.com.au/openapi.json)\n- [Canonical quote capability manifest](https://quotes.moveroo.com.au/quote-capability.json)\n- [Canonical AI plugin compatibility manifest](https://quotes.moveroo.com.au/.well-known/ai-plugin.json)\n\n## Public Agent API Endpoints\n\n- Household quote API: https://quotes.moveroo.com.au/api/v1/household-quotes/assistant/submit\n- Vehicle quote API: https://quotes.moveroo.com.au/api/v1/vehicle-quotes/assistant/submit\n- Callback request API: https://quotes.moveroo.com.au/api/v1/callbacks/assistant/request\n\nAgents may submit household quote, vehicle quote, or callback requests only when the customer has asked for that action and the payload includes the required customer consent fields.\n";

	return new Response(body, {
		headers: {
			"Content-Type": "text/markdown; charset=utf-8",
			"Cache-Control": "public, max-age=300",
			Link: '<https://moveroo.com.au/>; rel="canonical"',
			"X-Robots-Tag": "noindex, follow",
		},
	});
};
